language: php
php:
  - 5.5

before_script:
  - composer install --dev

script: vendor/bin/phpspec run -nq

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/coverage.xml

notifications:
  email:
    - info@gorka.io
